import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/animation/numericCounter.ts',
    'src/animation/rollerNumber.ts',
    'src/constants/enum.ts',
    'src/constants/regex.ts',
    'src/conversion/chineseCharacter.ts',
    'src/conversion/chineseCurrency.ts',
    'src/finance/expressions.ts',
    'src/finance/sequence.ts',
    'src/formatting/currency.ts',
    'src/formatting/padZero.ts',
    'src/math/computeExpression.ts',
    'src/math/math.ts',
    'src/math/unitConversion.ts',
    'src/network/CIDR.ts',
    'src/parse/idCard.ts',
    'src/parse/numberDetails.ts',
    'src/parse/rangeMap.ts',
    'src/validation/index.ts',
  ],
  dts: true,
  minify: true,
  format: ['cjs', 'esm'],
  outDir: 'dist',
  clean: true,
  sourcemap: true,
  splitting: true,
  treeshake: true,
});
