/**
 * ISO 4217 货币代码枚举
 *
 * @link locale list https://en.wikipedia.org/wiki/ISO_4217#Active_codes_(list_one)
 *
 */
export enum CurrencyCode {
  /** 阿联酋迪拉姆 */
  AED = 'AED',
  /** 阿富汗尼 */
  AFN = 'AFN',
  /** 阿尔巴尼亚列克 */
  ALL = 'ALL',
  /** 亚美尼亚德拉姆 */
  AMD = 'AMD',
  /** 荷属安的列斯盾 */
  ANG = 'ANG',
  /** 安哥拉宽扎 */
  AOA = 'AOA',
  /** 阿根廷比索 */
  ARS = 'ARS',
  /** 澳大利亚元 */
  AUD = 'AUD',
  /** 阿鲁巴弗罗林 */
  AWG = 'AWG',
  /** 阿塞拜疆马纳特 */
  AZN = 'AZN',
  /** 波斯尼亚和黑塞哥维那可兑换马克 */
  BAM = 'BAM',
  /** 巴巴多斯元 */
  BBD = 'BBD',
  /** 孟加拉塔卡 */
  BDT = 'BDT',
  /** 保加利亚列弗 */
  BGN = 'BGN',
  /** 巴林第纳尔 */
  BHD = 'BHD',
  /** 布隆迪法郎 */
  BIF = 'BIF',
  /** 百慕大元 */
  BMD = 'BMD',
  /** 文莱元 */
  BND = 'BND',
  /** 玻利维亚诺 */
  BOB = 'BOB',
  /** 玻利维亚 Mvdol（资金代码） */
  BOV = 'BOV',
  /** 巴西雷亚尔 */
  BRL = 'BRL',
  /** 巴哈马元 */
  BSD = 'BSD',
  /** 不丹努尔特鲁姆 */
  BTN = 'BTN',
  /** 博茨瓦纳普拉 */
  BWP = 'BWP',
  /** 白俄罗斯卢布 */
  BYN = 'BYN',
  /** 伯利兹元 */
  BZD = 'BZD',
  /** 加拿大元 */
  CAD = 'CAD',
  /** 刚果法郎 */
  CDF = 'CDF',
  /** WIR欧元（补充货币） */
  CHE = 'CHE',
  /** 瑞士法郎 */
  CHF = 'CHF',
  /** WIR法郎（补充货币） */
  CHW = 'CHW',
  /** 智利发展单位（资金代码） */
  CLF = 'CLF',
  /** 智利比索 */
  CLP = 'CLP',
  /** 人民币 */
  CNY = 'CNY',
  /** 哥伦比亚比索 */
  COP = 'COP',
  /** 哥伦比亚实际价值单位（资金代码） */
  COU = 'COU',
  /** 哥斯达黎加科朗 */
  CRC = 'CRC',
  /** 古巴比索 */
  CUP = 'CUP',
  /** 佛得角埃斯库多 */
  CVE = 'CVE',
  /** 捷克克朗 */
  CZK = 'CZK',
  /** 吉布提法郎 */
  DJF = 'DJF',
  /** 丹麦克朗 */
  DKK = 'DKK',
  /** 多米尼加比索 */
  DOP = 'DOP',
  /** 阿尔及利亚第纳尔 */
  DZD = 'DZD',
  /** 埃及镑 */
  EGP = 'EGP',
  /** 厄立特里亚纳克法 */
  ERN = 'ERN',
  /** 埃塞俄比亚比尔 */
  ETB = 'ETB',
  /** 欧元 */
  EUR = 'EUR',
  /** 斐济元 */
  FJD = 'FJD',
  /** 福克兰群岛镑 */
  FKP = 'FKP',
  /** 英镑 */
  GBP = 'GBP',
  /** 格鲁吉亚拉里 */
  GEL = 'GEL',
  /** 加纳塞地 */
  GHS = 'GHS',
  /** 直布罗陀镑 */
  GIP = 'GIP',
  /** 冈比亚达拉西 */
  GMD = 'GMD',
  /** 几内亚法郎 */
  GNF = 'GNF',
  /** 危地马拉格查尔 */
  GTQ = 'GTQ',
  /** 圭亚那元 */
  GYD = 'GYD',
  /** 港元 */
  HKD = 'HKD',
  /** 洪都拉斯伦皮拉 */
  HNL = 'HNL',
  /** 海地古德 */
  HTG = 'HTG',
  /** 匈牙利福林 */
  HUF = 'HUF',
  /** 印度尼西亚卢比 */
  IDR = 'IDR',
  /** 以色列新谢克尔 */
  ILS = 'ILS',
  /** 印度卢比 */
  INR = 'INR',
  /** 伊拉克第纳尔 */
  IQD = 'IQD',
  /** 伊朗里亚尔 */
  IRR = 'IRR',
  /** 冰岛克朗 */
  ISK = 'ISK',
  /** 牙买加元 */
  JMD = 'JMD',
  /** 约旦第纳尔 */
  JOD = 'JOD',
  /** 日元 */
  JPY = 'JPY',
  /** 肯尼亚先令 */
  KES = 'KES',
  /** 吉尔吉斯斯坦索姆 */
  KGS = 'KGS',
  /** 柬埔寨瑞尔 */
  KHR = 'KHR',
  /** 科摩罗法郎 */
  KMF = 'KMF',
  /** 朝鲜元 */
  KPW = 'KPW',
  /** 韩元 */
  KRW = 'KRW',
  /** 科威特第纳尔 */
  KWD = 'KWD',
  /** 开曼群岛元 */
  KYD = 'KYD',
  /** 哈萨克斯坦坚戈 */
  KZT = 'KZT',
  /** 老挝基普 */
  LAK = 'LAK',
  /** 黎巴嫩镑 */
  LBP = 'LBP',
  /** 斯里兰卡卢比 */
  LKR = 'LKR',
  /** 利比里亚元 */
  LRD = 'LRD',
  /** 莱索托洛蒂 */
  LSL = 'LSL',
  /** 利比亚第纳尔 */
  LYD = 'LYD',
  /** 摩洛哥迪拉姆 */
  MAD = 'MAD',
  /** 摩尔多瓦列伊 */
  MDL = 'MDL',
  /** 马达加斯加阿里亚里 */
  MGA = 'MGA',
  /** 马其顿代纳尔 */
  MKD = 'MKD',
  /** 缅甸元 */
  MMK = 'MMK',
  /** 蒙古图格里克 */
  MNT = 'MNT',
  /** 澳门元 */
  MOP = 'MOP',
  /** 毛里塔尼亚乌吉亚 */
  MRU = 'MRU',
  /** 毛里求斯卢比 */
  MUR = 'MUR',
  /** 马尔代夫卢菲亚 */
  MVR = 'MVR',
  /** 马拉维克瓦查 */
  MWK = 'MWK',
  /** 墨西哥比索 */
  MXN = 'MXN',
  /** 墨西哥投资单位 */
  MXV = 'MXV',
  /** 马来西亚林吉特 */
  MYR = 'MYR',
  /** 莫桑比克梅蒂卡尔 */
  MZN = 'MZN',
  /** 纳米比亚元 */
  NAD = 'NAD',
  /** 尼日利亚奈拉 */
  NGN = 'NGN',
  /** 尼加拉瓜科多巴 */
  NIO = 'NIO',
  /** 挪威克朗 */
  NOK = 'NOK',
  /** 尼泊尔卢比 */
  NPR = 'NPR',
  /** 新西兰元 */
  NZD = 'NZD',
  /** 阿曼里亚尔 */
  OMR = 'OMR',
  /** 巴拿马巴波亚 */
  PAB = 'PAB',
  /** 秘鲁索尔 */
  PEN = 'PEN',
  /** 巴布亚新几内亚基那 */
  PGK = 'PGK',
  /** 菲律宾比索 */
  PHP = 'PHP',
  /** 巴基斯坦卢比 */
  PKR = 'PKR',
  /** 波兰兹罗提 */
  PLN = 'PLN',
  /** 巴拉圭瓜拉尼 */
  PYG = 'PYG',
  /** 卡塔尔里亚尔 */
  QAR = 'QAR',
  /** 罗马尼亚列伊 */
  RON = 'RON',
  /** 塞尔维亚第纳尔 */
  RSD = 'RSD',
  /** 俄罗斯卢布 */
  RUB = 'RUB',
  /** 卢旺达法郎 */
  RWF = 'RWF',
  /** 沙特里亚尔 */
  SAR = 'SAR',
  /** 所罗门群岛元 */
  SBD = 'SBD',
  /** 塞舌尔卢比 */
  SCR = 'SCR',
  /** 苏丹镑 */
  SDG = 'SDG',
  /** 瑞典克朗 */
  SEK = 'SEK',
  /** 新加坡元 */
  SGD = 'SGD',
  /** 圣赫勒拿镑 */
  SHP = 'SHP',
  /** 塞拉利昂利昂（新利昂） */
  SLE = 'SLE',
  /** 索马里先令 */
  SOS = 'SOS',
  /** 苏里南元 */
  SRD = 'SRD',
  /** 南苏丹镑 */
  SSP = 'SSP',
  /** 圣多美和普林西比多布拉 */
  STN = 'STN',
  /** 萨尔瓦多科朗 */
  SVC = 'SVC',
  /** 叙利亚镑 */
  SYP = 'SYP',
  /** 斯威士兰里兰吉尼 */
  SZL = 'SZL',
  /** 泰铢 */
  THB = 'THB',
  /** 塔吉克斯坦索莫尼 */
  TJS = 'TJS',
  /** 土库曼斯坦马纳特 */
  TMT = 'TMT',
  /** 突尼斯第纳尔 */
  TND = 'TND',
  /** 汤加潘加 */
  TOP = 'TOP',
  /** 土耳其里拉 */
  TRY = 'TRY',
  /** 特立尼达和多巴哥元 */
  TTD = 'TTD',
  /** 新台币 */
  TWD = 'TWD',
  /** 坦桑尼亚先令 */
  TZS = 'TZS',
  /** 乌克兰格里夫纳 */
  UAH = 'UAH',
  /** 乌干达先令 */
  UGX = 'UGX',
  /** 美元 */
  USD = 'USD',
  /** 美元（次日）（资金代码） */
  USN = 'USN',
  /** 乌拉圭比索（索引单位）（资金代码） */
  UYI = 'UYI',
  /** 乌拉圭比索 */
  UYU = 'UYU',
  /** 乌拉圭名义工资指数单位 */
  UYW = 'UYW',
  /** 乌兹别克斯坦索姆 */
  UZS = 'UZS',
  /** 委内瑞拉数字玻利瓦尔 */
  VED = 'VED',
  /** 委内瑞拉主权玻利瓦尔 */
  VES = 'VES',
  /** 越南盾 */
  VND = 'VND',
  /** 瓦努阿图瓦图 */
  VUV = 'VUV',
  /** 萨摩亚塔拉 */
  WST = 'WST',
  /** 中非法郎 */
  XAF = 'XAF',
  /** 银（盎司） */
  XAG = 'XAG',
  /** 金（盎司） */
  XAU = 'XAU',
  /** 欧洲复合单位 */
  XBA = 'XBA',
  /** 欧洲货币单位 */
  XBB = 'XBB',
  /** 欧洲账户单位 */
  XBC = 'XBC',
  /** 欧洲账户单位 */
  XBD = 'XBD',
  /** 东加勒比元 */
  XCD = 'XCD',
  /** 特别提款权 */
  XDR = 'XDR',
  /** 西非法郎 */
  XOF = 'XOF',
  /** 钯（盎司） */
  XPD = 'XPD',
  /** 太平洋法郎 */
  XPF = 'XPF',
  /** 铂（盎司） */
  XPT = 'XPT',
  /** 苏克雷 */
  XSU = 'XSU',
  /** 为测试预留的代码 */
  XTS = 'XTS',
  /** 非洲开发银行计价单位 */
  XUA = 'XUA',
  /** 无币种 */
  XXX = 'XXX',
  /** 也门里亚尔 */
  YER = 'YER',
  /** 南非兰特 */
  ZAR = 'ZAR',
  /** 赞比亚克瓦查 */
  ZMW = 'ZMW',
  /** 津巴布韦元 */
  ZWG = 'ZWG',
  /** 津巴布韦元 */
  ZWL = 'ZWL',
}

/**
 * 度量单位枚举
 *
 * @link unit list https://tc39.es/ecma402/#table-sanctioned-single-unit-identifiers
 *
 */
export enum CurrencyUnit {
  /** 英亩 */
  Acre = 'acre',
  /** 比特 */
  Bit = 'bit',
  /** 字节 */
  Byte = 'byte',
  /** 摄氏度 */
  Celsius = 'celsius',
  /** 厘米 */
  Centimeter = 'centimeter',
  /** 天 */
  Day = 'day',
  /** 度 */
  Degree = 'degree',
  /** 华氏度 */
  Fahrenheit = 'fahrenheit',
  /** 液量盎司 */
  FluidOunce = 'fluid-ounce',
  /** 英尺 */
  Foot = 'foot',
  /** 加仑 */
  Gallon = 'gallon',
  /** 吉比特 */
  Gigabit = 'gigabit',
  /** 吉字节 */
  Gigabyte = 'gigabyte',
  /** 克 */
  Gram = 'gram',
  /** 公顷 */
  Hectare = 'hectare',
  /** 小时 */
  Hour = 'hour',
  /** 英寸 */
  Inch = 'inch',
  /** 千比特 */
  Kilobit = 'kilobit',
  /** 千字节 */
  Kilobyte = 'kilobyte',
  /** 千克 */
  Kilogram = 'kilogram',
  /** 千米 */
  Kilometer = 'kilometer',
  /** 升 */
  Liter = 'liter',
  /** 兆比特 */
  Megabit = 'megabit',
  /** 兆字节 */
  Megabyte = 'megabyte',
  /** 米 */
  Meter = 'meter',
  /** 微秒 */
  Microsecond = 'microsecond',
  /** 英里 */
  Mile = 'mile',
  /** 斯堪的纳维亚英里 */
  MileScandinavian = 'mile-scandinavian',
  /** 毫升 */
  Milliliter = 'milliliter',
  /** 毫米 */
  Millimeter = 'millimeter',
  /** 毫秒 */
  Millisecond = 'millisecond',
  /** 分钟 */
  Minute = 'minute',
  /** 月 */
  Month = 'month',
  /** 纳秒 */
  Nanosecond = 'nanosecond',
  /** 盎司 */
  Ounce = 'ounce',
  /** 百分比 */
  Percent = 'percent',
  /** 拍字节 */
  Petabyte = 'petabyte',
  /** 磅 */
  Pound = 'pound',
  /** 秒 */
  Second = 'second',
  /** 英石 */
  Stone = 'stone',
  /** 太比特 */
  Terabit = 'terabit',
  /** 太字节 */
  Terabyte = 'terabyte',
  /** 周 */
  Week = 'week',
  /** 码 */
  Yard = 'yard',
  /** 年 */
  Year = 'year',
}
